dist: trusty
sudo: false
language: node_js
node_js:
- 8.4.0
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: fBe2TZZb9fpXZq9nsY3FtMpWZpJukc5qVDXuUJrOxblq9aLsW84xvoSdq0mkY7M6Rlj26JTdfVvQwq4YpkLiz0Zg2Bg5+9KdxtBX8yCjSLuLsBJKsi6R9peS4GNR2SJangWJ7VmGpABISZGEHA4ojB4D0Q812lP/U/RzEEEsa/+rOm1LFaObCJOB4hU3kFnjD9ZUslWUmQQtmUaVqjaZHtmCpPeyAhQOu0iPFq9B+qVJha2hvOZW/F2CE2avz13r3yWPpoVykIMSOQt0DyXqeHld6/L4mbvBb1C9DnoKs6WiwMxgy4PRCJ8yFbDCxkHy7R/N6UuZX4SOyIuplQC0DAA8ieyUjC/Bd3vWAO/9Iq5x7WViTZlb3TJtWboxPM+prchH1VSgpy789sRlA4fvg+QNP7jEDII8Ym4/LTuQwt5SzwfmwBzZHVmoZeRpoesFMvsc4ZVBbJ1RFOoOEh3PeOfxC0s92rPV+wraBGHM7Mu/8r6NJK1nV73GcOiO/L2AErwbPMmNjLWt9OE1+yqTdVNjGFHNn16xRkbfO2rrXtiE60RsMDWUSn2tkrk7GV248YVxZiYAjY4lKWecrvykzB/rCS3YeyTVeRCIiL0thQ/EE2aN0SGoyonlpGCgdxZdeCaiZ5mz0y+/VuP4H31Z8yYGALJO3S7I7KDh/Vrduks=
  - secure: jqk8Q/htNtesLkKjFKhRqHBG86+0WRbGu7lKvOHgwZp+ZYLohNT9S+BKnmxtw1WLfnuwla1Yluv8EGkll6IdyzcfrtyScBgQUDx1OvCtyJr+5ur/LSTRpU2Jh2D6RAz5cQ3TcIl/zgouQddFAQXudT/XsSVQFl9OnTqgdLkgtud6FYkSinLZbSboJkVthGXbJ9yv3H4fQr9472r8r7+Oyl23V0Goqo97kJ/w4Ps17avRvKZsI6Si7VyjCPf17hBWqZ9z6M2L5EyHDJKYG96l1Xm4i+0gCQXXr9g+zuZgkL0AhnTBO7P/6utqAeDOqA2kTpkITqYEhbQHWczMDAa91DNmIq/PibPWd6BQziBboqd93Vp1aDvtPm2lNjgdfGzOE/3ghGkO5do4OVcgcvgdoEpdz17cYlqNCDI3er+gYux10YIoJb/b8Cjn8GEUYrAH9qTvEQcOLvC7SqrKXYB1+NRGA54ZA+f+cML6pb4BHwSYUBprJ7p4JjOe9NeQgp2RlZUnvUdRYecahjXVHRKkz1h40+LyCSCGRrR6PK9Mvg+2gorCFIZnkAc4GCske/sS4azUFKzzy+ILRTqHg1vpy4dr8b1SxsKAndT/uUAzvlvrBcCcji85qZnV2vs/K3uSydvLoDtj/evA1nYrzsCrGlyVGOxIiTHJo0z64j/1TrU=
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T7BPVSAR3
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
cache:
  directories:
  - $HOME/.npm
deploy:
  provider: releases
  api_key:
    secure: Mw/QvM8Pnr6aU/tnc6E75diHdkDm/dAWoW3U7qhnmRhbpi7oi2yUt0ekAzK51+bBxP52knJ+sjpAnKV61JWsLUAxxXvny3ty4D8H98myWI17nqDVmd+HI62i7bNRk5GrXL6rrVH+H3/k2H287T0pUj6xB3qsQTS5tl3jksrgnwjOyDoDW+G/N+or9STvjsD7jEGLUTLMAg035mep9+SAq1hI4MPxmLVqIf7HBrV4YmN+b4z+KOnZlRmg/R2e3N3yMzu/TxuVz7s+5QiHT0QKByIBDlWV9736+wmiOcdXXrnFkLMdoLFYo7zpOHEUHM16hJJqO47HMKXUFUAeiYSbfPBc7jS4iROFK2qoiGPHe5V9Ag3GIgKKnro49XX1S+X710JjyGGGTfAlIyoJPDKdgLwsn8mf22oNtJl6gfKbXGcHI6k81uoj0I+8bvyqJICw6Jacp2gsK9DlGhp71PLFzdelvVItqq6CbnQPKZMzHedb3xOqRuXqecv3ewGT/MKjjti0qjUsEtZY+U7/AjQKXDU1OsM8ipgfvPKjU1E4+rYeRWv3mEEiZsD+w6ZiapXi/lRIEQB7J/u5budRNCoVfcFmfDeNGyqNCx15gCkK06uAJEUyRudCnjuI3VyjXPmQcgPPA0x5bTc6O2ATYBZWRYPa1WoSuPLi9Ok+3d9unTU=
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-(m|rc)\.[0-9]+)?$
after_deploy:
- bash scripts/npm-publish.bash --access public
- bash scripts/gh-publish.bash $TRAVIS_REPO_SLUG
